---
loglevel: debug
server: tcp://localhost:1705
streams:
  Canard:
    clients:
      - canard
  Kitchen:
    clients:
      - kitchen
  Bedroom Mark:
    clients:
      - bedroom-mark
  Party 1:
    clients:
      - canard
      - bedroom-mark
      - kitchen
    volume:
      kitchen: 70
  Party 2:
    clients:
      - canard
      - kitchen
